export default function useContries() {
  return {
    countries,
  };
}

const countries = [
  {
    code: 'cu',
    esName: 'Cuba',
    enName: 'Cuba',
    callingCode: '53',
  },
  {
    code: 'us',
    esName: 'Estados Unidos',
    enName: 'United States',
    callingCode: '1',
  },
  {
    code: 'es',
    esName: 'España',
    enName: 'Spain',
    callingCode: '34',
  },
  {
    code: 'mx',
    esName: 'México',
    enName: 'Mexico',
    callingCode: '52',
  },
  {
    code: 'it',
    esName: 'Italia',
    enName: 'Italy',
    callingCode: '39',
  },
  {
    code: 'ad',
    esName: 'Andorra',
    enName: 'Andorra',
    callingCode: '376',
  },
  {
    code: 'ae',
    esName: 'Emiratos Árabes Unidos',
    enName: 'United Arab Emirates',
    callingCode: '971',
  },
  {
    code: 'af',
    esName: 'Afganistán',
    enName: 'Afghanistan',
    callingCode: '93',
  },
  {
    code: 'ag',
    esName: 'Antigua y Barbuda',
    enName: 'Antigua and Barbuda',
    callingCode: '1',
  },
  {
    code: 'ai',
    esName: 'Anguila',
    enName: 'Anguilla',
    callingCode: '1',
  },
  {
    code: 'al',
    esName: 'Albania',
    enName: 'Albania',
    callingCode: '355',
  },
  {
    code: 'am',
    esName: 'Armenia',
    enName: 'Armenia',
    callingCode: '374',
  },
  {
    code: 'ao',
    esName: 'Angola',
    enName: 'Angola',
    callingCode: '244',
  },
  {
    code: 'ar',
    esName: 'Argentina',
    enName: 'Argentina',
    callingCode: '54',
  },
  {
    code: 'as',
    esName: 'Samoa Americana',
    enName: 'American Samoa',
    callingCode: '1',
  },
  {
    code: 'at',
    esName: 'Austria',
    enName: 'Austria',
    callingCode: '43',
  },
  {
    code: 'au',
    esName: 'Australia',
    enName: 'Australia',
    callingCode: '61',
  },
  {
    code: 'aw',
    esName: 'Aruba',
    enName: 'Aruba',
    callingCode: '297',
  },
  {
    code: 'ax',
    esName: 'Åland',
    enName: 'Åland Islands',
    callingCode: '358',
  },
  {
    code: 'az',
    esName: 'Azerbaiyán',
    enName: 'Azerbaijan',
    callingCode: '994',
  },
  {
    code: 'ba',
    esName: 'Bosnia y Herzegovina',
    enName: 'Bosnia and Herzegovina',
    callingCode: '387',
  },
  {
    code: 'bb',
    esName: 'Barbados',
    enName: 'Barbados',
    callingCode: '1',
  },
  {
    code: 'bd',
    esName: 'Bangladesh',
    enName: 'Bangladesh',
    callingCode: '880',
  },
  {
    code: 'be',
    esName: 'Bélgica',
    enName: 'Belgium',
    callingCode: '32',
  },
  {
    code: 'bf',
    esName: 'Burkina Faso',
    enName: 'Burkina Faso',
    callingCode: '226',
  },
  {
    code: 'bg',
    esName: 'Bulgaria',
    enName: 'Bulgaria',
    callingCode: '359',
  },
  {
    code: 'bh',
    esName: 'Baréin',
    enName: 'Bahrain',
    callingCode: '973',
  },
  {
    code: 'bi',
    esName: 'Burundi',
    enName: 'Burundi',
    callingCode: '257',
  },
  {
    code: 'bj',
    esName: 'Benín',
    enName: 'Benin',
    callingCode: '229',
  },
  {
    code: 'bl',
    esName: 'San Bartolomé',
    enName: 'Saint Barthélemy',
    callingCode: '590',
  },
  {
    code: 'bm',
    esName: 'Bermudas',
    enName: 'Bermuda',
    callingCode: '1',
  },
  {
    code: 'bn',
    esName: 'Brunéi',
    enName: 'Brunei',
    callingCode: '673',
  },
  {
    code: 'bo',
    esName: 'Bolivia',
    enName: 'Bolivia',
    callingCode: '591',
  },
  {
    code: 'bq',
    esName: 'Caribe Neerlandés',
    enName: 'Caribbean Netherlands',
    callingCode: '599',
  },
  {
    code: 'br',
    esName: 'Brasil',
    enName: 'Brazil',
    callingCode: '55',
  },
  {
    code: 'bs',
    esName: 'Bahamas',
    enName: 'Bahamas',
    callingCode: '1',
  },
  {
    code: 'bt',
    esName: 'Bután',
    enName: 'Bhutan',
    callingCode: '975',
  },
  {
    code: 'bw',
    esName: 'Botsuana',
    enName: 'Botswana',
    callingCode: '267',
  },
  {
    code: 'by',
    esName: 'Bielorrusia',
    enName: 'Belarus',
    callingCode: '375',
  },
  {
    code: 'bz',
    esName: 'Belice',
    enName: 'Belize',
    callingCode: '501',
  },
  {
    code: 'ca',
    esName: 'Canadá',
    enName: 'Canada',
    callingCode: '1',
  },
  {
    code: 'cc',
    esName: 'Islas Cocos',
    enName: 'Cocos (Keeling) Islands',
    callingCode: '61',
  },
  {
    code: 'cd',
    esName: 'Congo (Rep. Dem.)',
    enName: 'DR Congo',
    callingCode: '243',
  },
  {
    code: 'cf',
    esName: 'República Centroafricana',
    enName: 'Central African Republic',
    callingCode: '236',
  },
  {
    code: 'cg',
    esName: 'Congo',
    enName: 'Republic of the Congo',
    callingCode: '242',
  },
  {
    code: 'ch',
    esName: 'Suiza',
    enName: 'Switzerland',
    callingCode: '41',
  },
  {
    code: 'ci',
    esName: 'Costa de Marfil',
    enName: "Côte d'Ivoire (Ivory Coast)",
    callingCode: '225',
  },
  {
    code: 'ck',
    esName: 'Islas Cook',
    enName: 'Cook Islands',
    callingCode: '682',
  },
  {
    code: 'cl',
    esName: 'Chile',
    enName: 'Chile',
    callingCode: '56',
  },
  {
    code: 'cm',
    esName: 'Camerún',
    enName: 'Cameroon',
    callingCode: '237',
  },
  {
    code: 'cn',
    esName: 'China',
    enName: 'China',
    callingCode: '86',
  },
  {
    code: 'co',
    esName: 'Colombia',
    enName: 'Colombia',
    callingCode: '57',
  },
  {
    code: 'cr',
    esName: 'Costa Rica',
    enName: 'Costa Rica',
    callingCode: '506',
  },
  {
    code: 'cv',
    esName: 'Cabo Verde',
    enName: 'Cape Verde',
    callingCode: '238',
  },
  {
    code: 'cw',
    esName: 'Curazao',
    enName: 'Curaçao',
    callingCode: '599',
  },
  {
    code: 'cx',
    esName: 'Isla de Navidad',
    enName: 'Christmas Island',
    callingCode: '61',
  },
  {
    code: 'cy',
    esName: 'Chipre',
    enName: 'Cyprus',
    callingCode: '357',
  },
  {
    code: 'cz',
    esName: 'República Checa',
    enName: 'Czechia',
    callingCode: '420',
  },
  {
    code: 'de',
    esName: 'Alemania',
    enName: 'Germany',
    callingCode: '49',
  },
  {
    code: 'dj',
    esName: 'Yibuti',
    enName: 'Djibouti',
    callingCode: '253',
  },
  {
    code: 'dk',
    esName: 'Dinamarca',
    enName: 'Denmark',
    callingCode: '45',
  },
  {
    code: 'dm',
    esName: 'Dominica',
    enName: 'Dominica',
    callingCode: '1',
  },
  {
    code: 'do',
    esName: 'República Dominicana',
    enName: 'Dominican Republic',
    callingCode: '1',
  },
  {
    code: 'dz',
    esName: 'Argelia',
    enName: 'Algeria',
    callingCode: '213',
  },
  {
    code: 'ec',
    esName: 'Ecuador',
    enName: 'Ecuador',
    callingCode: '593',
  },
  {
    code: 'ee',
    esName: 'Estonia',
    enName: 'Estonia',
    callingCode: '372',
  },
  {
    code: 'eg',
    esName: 'Egipto',
    enName: 'Egypt',
    callingCode: '20',
  },
  {
    code: 'eh',
    esName: 'Sahara Occidental',
    enName: 'Western Sahara',
    callingCode: '212',
  },
  {
    code: 'er',
    esName: 'Eritrea',
    enName: 'Eritrea',
    callingCode: '291',
  },
  {
    code: 'et',
    esName: 'Etiopía',
    enName: 'Ethiopia',
    callingCode: '251',
  },
  {
    code: 'fi',
    esName: 'Finlandia',
    enName: 'Finland',
    callingCode: '358',
  },
  {
    code: 'fj',
    esName: 'Fiyi',
    enName: 'Fiji',
    callingCode: '679',
  },
  {
    code: 'fk',
    esName: 'Islas Malvinas',
    enName: 'Falkland Islands',
    callingCode: '500',
  },
  {
    code: 'fm',
    esName: 'Micronesia',
    enName: 'Micronesia',
    callingCode: '691',
  },
  {
    code: 'fo',
    esName: 'Islas Feroe',
    enName: 'Faroe Islands',
    callingCode: '298',
  },
  {
    code: 'fr',
    esName: 'Francia',
    enName: 'France',
    callingCode: '33',
  },
  {
    code: 'ga',
    esName: 'Gabón',
    enName: 'Gabon',
    callingCode: '241',
  },
  {
    code: 'gb',
    esName: 'Reino Unido',
    enName: 'United Kingdom',
    callingCode: '44',
  },
  {
    code: 'gd',
    esName: 'Granada',
    enName: 'Grenada',
    callingCode: '1',
  },
  {
    code: 'ge',
    esName: 'Georgia',
    enName: 'Georgia',
    callingCode: '995',
  },
  {
    code: 'gf',
    esName: 'Guayana Francesa',
    enName: 'French Guiana',
    callingCode: '594',
  },
  {
    code: 'gg',
    esName: 'Guernsey',
    enName: 'Guernsey',
    callingCode: '44',
  },
  {
    code: 'gh',
    esName: 'Ghana',
    enName: 'Ghana',
    callingCode: '233',
  },
  {
    code: 'gi',
    esName: 'Gibraltar',
    enName: 'Gibraltar',
    callingCode: '350',
  },
  {
    code: 'gl',
    esName: 'Groenlandia',
    enName: 'Greenland',
    callingCode: '299',
  },
  {
    code: 'gm',
    esName: 'Gambia',
    enName: 'Gambia',
    callingCode: '220',
  },
  {
    code: 'gn',
    esName: 'Guinea',
    enName: 'Guinea',
    callingCode: '224',
  },
  {
    code: 'gp',
    esName: 'Guadalupe',
    enName: 'Guadeloupe',
    callingCode: '590',
  },
  {
    code: 'gq',
    esName: 'Guinea Ecuatorial',
    enName: 'Equatorial Guinea',
    callingCode: '240',
  },
  {
    code: 'gr',
    esName: 'Grecia',
    enName: 'Greece',
    callingCode: '30',
  },
  {
    code: 'gt',
    esName: 'Guatemala',
    enName: 'Guatemala',
    callingCode: '502',
  },
  {
    code: 'gu',
    esName: 'Guam',
    enName: 'Guam',
    callingCode: '1',
  },
  {
    code: 'gw',
    esName: 'Guinea-Bisáu',
    enName: 'Guinea-Bissau',
    callingCode: '245',
  },
  {
    code: 'gy',
    esName: 'Guyana',
    enName: 'Guyana',
    callingCode: '592',
  },
  {
    code: 'hk',
    esName: 'Hong Kong',
    enName: 'Hong Kong',
    callingCode: '852',
  },
  {
    code: 'hn',
    esName: 'Honduras',
    enName: 'Honduras',
    callingCode: '504',
  },
  {
    code: 'hr',
    esName: 'Croacia',
    enName: 'Croatia',
    callingCode: '385',
  },
  {
    code: 'ht',
    esName: 'Haití',
    enName: 'Haiti',
    callingCode: '509',
  },
  {
    code: 'hu',
    esName: 'Hungría',
    enName: 'Hungary',
    callingCode: '36',
  },
  {
    code: 'id',
    esName: 'Indonesia',
    enName: 'Indonesia',
    callingCode: '62',
  },
  {
    code: 'ie',
    esName: 'Irlanda',
    enName: 'Ireland',
    callingCode: '353',
  },
  {
    code: 'il',
    esName: 'Israel',
    enName: 'Israel',
    callingCode: '972',
  },
  {
    code: 'im',
    esName: 'Isla de Man',
    enName: 'Isle of Man',
    callingCode: '44',
  },
  {
    code: 'in',
    esName: 'India',
    enName: 'India',
    callingCode: '91',
  },
  {
    code: 'io',
    esName: 'Territorio Británico del Océano Índico',
    enName: 'British Indian Ocean Territory',
    callingCode: '246',
  },
  {
    code: 'iq',
    esName: 'Irak',
    enName: 'Iraq',
    callingCode: '964',
  },
  {
    code: 'ir',
    esName: 'Irán',
    enName: 'Iran',
    callingCode: '98',
  },
  {
    code: 'is',
    esName: 'Islandia',
    enName: 'Iceland',
    callingCode: '354',
  },
  {
    code: 'je',
    esName: 'Jersey',
    enName: 'Jersey',
    callingCode: '44',
  },
  {
    code: 'jm',
    esName: 'Jamaica',
    enName: 'Jamaica',
    callingCode: '1',
  },
  {
    code: 'jo',
    esName: 'Jordania',
    enName: 'Jordan',
    callingCode: '962',
  },
  {
    code: 'jp',
    esName: 'Japón',
    enName: 'Japan',
    callingCode: '81',
  },
  {
    code: 'ke',
    esName: 'Kenia',
    enName: 'Kenya',
    callingCode: '254',
  },
  {
    code: 'kg',
    esName: 'Kirguistán',
    enName: 'Kyrgyzstan',
    callingCode: '996',
  },
  {
    code: 'kh',
    esName: 'Camboya',
    enName: 'Cambodia',
    callingCode: '855',
  },
  {
    code: 'ki',
    esName: 'Kiribati',
    enName: 'Kiribati',
    callingCode: '686',
  },
  {
    code: 'km',
    esName: 'Comoras',
    enName: 'Comoros',
    callingCode: '269',
  },
  {
    code: 'kn',
    esName: 'San Cristóbal y Nieves',
    enName: 'Saint Kitts and Nevis',
    callingCode: '1',
  },
  {
    code: 'kp',
    esName: 'Corea del Norte',
    enName: 'North Korea',
    callingCode: '850',
  },
  {
    code: 'kr',
    esName: 'Corea del Sur',
    enName: 'South Korea',
    callingCode: '82',
  },
  {
    code: 'kw',
    esName: 'Kuwait',
    enName: 'Kuwait',
    callingCode: '965',
  },
  {
    code: 'ky',
    esName: 'Islas Caimán',
    enName: 'Cayman Islands',
    callingCode: '1',
  },
  {
    code: 'kz',
    esName: 'Kazajistán',
    enName: 'Kazakhstan',
    callingCode: '7',
  },
  {
    code: 'la',
    esName: 'Laos',
    enName: 'Laos',
    callingCode: '856',
  },
  {
    code: 'lb',
    esName: 'Líbano',
    enName: 'Lebanon',
    callingCode: '961',
  },
  {
    code: 'lc',
    esName: 'Santa Lucía',
    enName: 'Saint Lucia',
    callingCode: '1',
  },
  {
    code: 'li',
    esName: 'Liechtenstein',
    enName: 'Liechtenstein',
    callingCode: '423',
  },
  {
    code: 'lk',
    esName: 'Sri Lanka',
    enName: 'Sri Lanka',
    callingCode: '94',
  },
  {
    code: 'lr',
    esName: 'Liberia',
    enName: 'Liberia',
    callingCode: '231',
  },
  {
    code: 'ls',
    esName: 'Lesoto',
    enName: 'Lesotho',
    callingCode: '266',
  },
  {
    code: 'lt',
    esName: 'Lituania',
    enName: 'Lithuania',
    callingCode: '370',
  },
  {
    code: 'lu',
    esName: 'Luxemburgo',
    enName: 'Luxembourg',
    callingCode: '352',
  },
  {
    code: 'lv',
    esName: 'Letonia',
    enName: 'Latvia',
    callingCode: '371',
  },
  {
    code: 'ly',
    esName: 'Libia',
    enName: 'Libya',
    callingCode: '218',
  },
  {
    code: 'ma',
    esName: 'Marruecos',
    enName: 'Morocco',
    callingCode: '212',
  },
  {
    code: 'mc',
    esName: 'Mónaco',
    enName: 'Monaco',
    callingCode: '377',
  },
  {
    code: 'md',
    esName: 'Moldavia',
    enName: 'Moldova',
    callingCode: '373',
  },
  {
    code: 'me',
    esName: 'Montenegro',
    enName: 'Montenegro',
    callingCode: '382',
  },
  {
    code: 'mf',
    esName: 'San Martín (Francia)',
    enName: 'Saint Martin',
    callingCode: '590',
  },
  {
    code: 'mg',
    esName: 'Madagascar',
    enName: 'Madagascar',
    callingCode: '261',
  },
  {
    code: 'mh',
    esName: 'Islas Marshall',
    enName: 'Marshall Islands',
    callingCode: '692',
  },
  {
    code: 'mk',
    esName: 'Macedonia del Norte',
    enName: 'North Macedonia',
    callingCode: '389',
  },
  {
    code: 'ml',
    esName: 'Malí',
    enName: 'Mali',
    callingCode: '223',
  },
  {
    code: 'mm',
    esName: 'Myanmar',
    enName: 'Myanmar',
    callingCode: '95',
  },
  {
    code: 'mn',
    esName: 'Mongolia',
    enName: 'Mongolia',
    callingCode: '976',
  },
  {
    code: 'mo',
    esName: 'Macao',
    enName: 'Macau',
    callingCode: '853',
  },
  {
    code: 'mp',
    esName: 'Islas Marianas del Norte',
    enName: 'Northern Mariana Islands',
    callingCode: '1',
  },
  {
    code: 'mq',
    esName: 'Martinica',
    enName: 'Martinique',
    callingCode: '596',
  },
  {
    code: 'mr',
    esName: 'Mauritania',
    enName: 'Mauritania',
    callingCode: '222',
  },
  {
    code: 'ms',
    esName: 'Montserrat',
    enName: 'Montserrat',
    callingCode: '1',
  },
  {
    code: 'mt',
    esName: 'Malta',
    enName: 'Malta',
    callingCode: '356',
  },
  {
    code: 'mu',
    esName: 'Mauricio',
    enName: 'Mauritius',
    callingCode: '230',
  },
  {
    code: 'mv',
    esName: 'Maldivas',
    enName: 'Maldives',
    callingCode: '960',
  },
  {
    code: 'mw',
    esName: 'Malawi',
    enName: 'Malawi',
    callingCode: '265',
  },
  {
    code: 'my',
    esName: 'Malasia',
    enName: 'Malaysia',
    callingCode: '60',
  },
  {
    code: 'mz',
    esName: 'Mozambique',
    enName: 'Mozambique',
    callingCode: '258',
  },
  {
    code: 'na',
    esName: 'Namibia',
    enName: 'Namibia',
    callingCode: '264',
  },
  {
    code: 'nc',
    esName: 'Nueva Caledonia',
    enName: 'New Caledonia',
    callingCode: '687',
  },
  {
    code: 'ne',
    esName: 'Níger',
    enName: 'Niger',
    callingCode: '227',
  },
  {
    code: 'nf',
    esName: 'Isla Norfolk',
    enName: 'Norfolk Island',
    callingCode: '672',
  },
  {
    code: 'ng',
    esName: 'Nigeria',
    enName: 'Nigeria',
    callingCode: '234',
  },
  {
    code: 'ni',
    esName: 'Nicaragua',
    enName: 'Nicaragua',
    callingCode: '505',
  },
  {
    code: 'nl',
    esName: 'Países Bajos',
    enName: 'Netherlands',
    callingCode: '31',
  },
  {
    code: 'no',
    esName: 'Noruega',
    enName: 'Norway',
    callingCode: '47',
  },
  {
    code: 'np',
    esName: 'Nepal',
    enName: 'Nepal',
    callingCode: '977',
  },
  {
    code: 'nr',
    esName: 'Nauru',
    enName: 'Nauru',
    callingCode: '674',
  },
  {
    code: 'nu',
    esName: 'Niue',
    enName: 'Niue',
    callingCode: '683',
  },
  {
    code: 'nz',
    esName: 'Nueva Zelanda',
    enName: 'New Zealand',
    callingCode: '64',
  },
  {
    code: 'om',
    esName: 'Omán',
    enName: 'Oman',
    callingCode: '968',
  },
  {
    code: 'pa',
    esName: 'Panamá',
    enName: 'Panama',
    callingCode: '507',
  },
  {
    code: 'pe',
    esName: 'Perú',
    enName: 'Peru',
    callingCode: '51',
  },
  {
    code: 'pf',
    esName: 'Polinesia Francesa',
    enName: 'French Polynesia',
    callingCode: '689',
  },
  {
    code: 'pg',
    esName: 'Papúa Nueva Guinea',
    enName: 'Papua New Guinea',
    callingCode: '675',
  },
  {
    code: 'ph',
    esName: 'Filipinas',
    enName: 'Philippines',
    callingCode: '63',
  },
  {
    code: 'pk',
    esName: 'Pakistán',
    enName: 'Pakistan',
    callingCode: '92',
  },
  {
    code: 'pl',
    esName: 'Polonia',
    enName: 'Poland',
    callingCode: '48',
  },
  {
    code: 'pm',
    esName: 'San Pedro y Miquelón',
    enName: 'Saint Pierre and Miquelon',
    callingCode: '508',
  },
  {
    code: 'pr',
    esName: 'Puerto Rico',
    enName: 'Puerto Rico',
    callingCode: '1',
  },
  {
    code: 'ps',
    esName: 'Palestina',
    enName: 'Palestine',
    callingCode: '970',
  },
  {
    code: 'pt',
    esName: 'Portugal',
    enName: 'Portugal',
    callingCode: '351',
  },
  {
    code: 'pw',
    esName: 'Palaos',
    enName: 'Palau',
    callingCode: '680',
  },
  {
    code: 'py',
    esName: 'Paraguay',
    enName: 'Paraguay',
    callingCode: '595',
  },
  {
    code: 'qa',
    esName: 'Catar',
    enName: 'Qatar',
    callingCode: '974',
  },
  {
    code: 're',
    esName: 'Reunión',
    enName: 'Réunion',
    callingCode: '262',
  },
  {
    code: 'ro',
    esName: 'Rumania',
    enName: 'Romania',
    callingCode: '40',
  },
  {
    code: 'rs',
    esName: 'Serbia',
    enName: 'Serbia',
    callingCode: '381',
  },
  {
    code: 'ru',
    esName: 'Rusia',
    enName: 'Russia',
    callingCode: '7',
  },
  {
    code: 'rw',
    esName: 'Ruanda',
    enName: 'Rwanda',
    callingCode: '250',
  },
  {
    code: 'sa',
    esName: 'Arabia Saudita',
    enName: 'Saudi Arabia',
    callingCode: '966',
  },
  {
    code: 'sb',
    esName: 'Islas Salomón',
    enName: 'Solomon Islands',
    callingCode: '677',
  },
  {
    code: 'sc',
    esName: 'Seychelles',
    enName: 'Seychelles',
    callingCode: '248',
  },
  {
    code: 'sd',
    esName: 'Sudán',
    enName: 'Sudan',
    callingCode: '249',
  },
  {
    code: 'se',
    esName: 'Suecia',
    enName: 'Sweden',
    callingCode: '46',
  },
  {
    code: 'sg',
    esName: 'Singapur',
    enName: 'Singapore',
    callingCode: '65',
  },
  {
    code: 'sh',
    esName: 'Santa Elena, Ascensión y Tristán de Acuña',
    enName: 'Saint Helena, Ascension and Tristan da Cunha',
    callingCode: '290',
  },
  {
    code: 'si',
    esName: 'Eslovenia',
    enName: 'Slovenia',
    callingCode: '386',
  },
  {
    code: 'sj',
    esName: 'Svalbard y Jan Mayen',
    enName: 'Svalbard and Jan Mayen',
    callingCode: '47',
  },
  {
    code: 'sk',
    esName: 'Eslovaquia',
    enName: 'Slovakia',
    callingCode: '421',
  },
  {
    code: 'sl',
    esName: 'Sierra Leona',
    enName: 'Sierra Leone',
    callingCode: '232',
  },
  {
    code: 'sm',
    esName: 'San Marino',
    enName: 'San Marino',
    callingCode: '378',
  },
  {
    code: 'sn',
    esName: 'Senegal',
    enName: 'Senegal',
    callingCode: '221',
  },
  {
    code: 'so',
    esName: 'Somalia',
    enName: 'Somalia',
    callingCode: '252',
  },
  {
    code: 'sr',
    esName: 'Surinam',
    enName: 'Suriname',
    callingCode: '597',
  },
  {
    code: 'ss',
    esName: 'Sudán del Sur',
    enName: 'South Sudan',
    callingCode: '211',
  },
  {
    code: 'st',
    esName: 'Santo Tomé y Príncipe',
    enName: 'São Tomé and Príncipe',
    callingCode: '239',
  },
  {
    code: 'sv',
    esName: 'El Salvador',
    enName: 'El Salvador',
    callingCode: '503',
  },
  {
    code: 'sx',
    esName: 'San Martín (Países Bajos)',
    enName: 'Sint Maarten',
    callingCode: '1',
  },
  {
    code: 'sy',
    esName: 'Siria',
    enName: 'Syria',
    callingCode: '963',
  },
  {
    code: 'sz',
    esName: 'Suazilandia',
    enName: 'Eswatini (Swaziland)',
    callingCode: '268',
  },
  {
    code: 'tc',
    esName: 'Islas Turcas y Caicos',
    enName: 'Turks and Caicos Islands',
    callingCode: '1',
  },
  {
    code: 'td',
    esName: 'Chad',
    enName: 'Chad',
    callingCode: '235',
  },
  {
    code: 'tg',
    esName: 'Togo',
    enName: 'Togo',
    callingCode: '228',
  },
  {
    code: 'th',
    esName: 'Tailandia',
    enName: 'Thailand',
    callingCode: '66',
  },
  {
    code: 'tj',
    esName: 'Tayikistán',
    enName: 'Tajikistan',
    callingCode: '992',
  },
  {
    code: 'tk',
    esName: 'Tokelau',
    enName: 'Tokelau',
    callingCode: '690',
  },
  {
    code: 'tl',
    esName: 'Timor Oriental',
    enName: 'Timor-Leste',
    callingCode: '670',
  },
  {
    code: 'tm',
    esName: 'Turkmenistán',
    enName: 'Turkmenistan',
    callingCode: '993',
  },
  {
    code: 'tn',
    esName: 'Túnez',
    enName: 'Tunisia',
    callingCode: '216',
  },
  {
    code: 'to',
    esName: 'Tonga',
    enName: 'Tonga',
    callingCode: '676',
  },
  {
    code: 'tr',
    esName: 'Turquía',
    enName: 'Turkey',
    callingCode: '90',
  },
  {
    code: 'tt',
    esName: 'Trinidad y Tobago',
    enName: 'Trinidad and Tobago',
    callingCode: '1',
  },
  {
    code: 'tv',
    esName: 'Tuvalu',
    enName: 'Tuvalu',
    callingCode: '688',
  },
  {
    code: 'tw',
    esName: 'Taiwán',
    enName: 'Taiwan',
    callingCode: '886',
  },
  {
    code: 'tz',
    esName: 'Tanzania',
    enName: 'Tanzania',
    callingCode: '255',
  },
  {
    code: 'ua',
    esName: 'Ucrania',
    enName: 'Ukraine',
    callingCode: '380',
  },
  {
    code: 'ug',
    esName: 'Uganda',
    enName: 'Uganda',
    callingCode: '256',
  },
  {
    code: 'uy',
    esName: 'Uruguay',
    enName: 'Uruguay',
    callingCode: '598',
  },
  {
    code: 'uz',
    esName: 'Uzbekistán',
    enName: 'Uzbekistan',
    callingCode: '998',
  },
  {
    code: 'va',
    esName: 'Ciudad del Vaticano',
    enName: 'Vatican City (Holy See)',
    callingCode: '39',
  },
  {
    code: 'vc',
    esName: 'San Vicente y las Granadinas',
    enName: 'Saint Vincent and the Grenadines',
    callingCode: '1',
  },
  {
    code: 've',
    esName: 'Venezuela',
    enName: 'Venezuela',
    callingCode: '58',
  },
  {
    code: 'vg',
    esName: 'Islas Vírgenes Británicas',
    enName: 'British Virgin Islands',
    callingCode: '1',
  },
  {
    code: 'vi',
    esName: 'Islas Vírgenes de los Estados Unidos',
    enName: 'United States Virgin Islands',
    callingCode: '1',
  },
  {
    code: 'vn',
    esName: 'Vietnam',
    enName: 'Vietnam',
    callingCode: '84',
  },
  {
    code: 'vu',
    esName: 'Vanuatu',
    enName: 'Vanuatu',
    callingCode: '678',
  },
  {
    code: 'wf',
    esName: 'Wallis y Futuna',
    enName: 'Wallis and Futuna',
    callingCode: '681',
  },
  {
    code: 'ws',
    esName: 'Samoa',
    enName: 'Samoa',
    callingCode: '685',
  },
  {
    code: 'xk',
    esName: 'Kosovo',
    enName: 'Kosovo',
    callingCode: '383',
  },
  {
    code: 'ye',
    esName: 'Yemen',
    enName: 'Yemen',
    callingCode: '967',
  },
  {
    code: 'yt',
    esName: 'Mayotte',
    enName: 'Mayotte',
    callingCode: '262',
  },
  {
    code: 'za',
    esName: 'Sudáfrica',
    enName: 'South Africa',
    callingCode: '27',
  },
  {
    code: 'zm',
    esName: 'Zambia',
    enName: 'Zambia',
    callingCode: '260',
  },
  {
    code: 'zw',
    esName: 'Zimbabue',
    enName: 'Zimbabwe',
    callingCode: '263',
  },
];
